CREATE TABLE guestbook_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    body TEXT NOT NULL,
    name TEXT DEFAULT NULL
);

CREATE TABLE journal_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL
);
