name = "leon-home"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

d1_databases = [
  { binding = "DB", database_name = "home-guestbook", database_id = "098931d9-36db-4950-912a-60efd16ef111", preview_database_id = "098931d9-36db-4950-912a-60efd16ef111" },
]